sudo: required

language: cpp
services:
  - docker

script:
  - chmod +x build.sh
  - docker build . -t wine.appimage
  - sudo cp "$(sudo find /var/lib/docker -name 'Wine-*x86_64.AppImage')" .
  - sudo chmod 777 Wine-*x86_64.AppImage

after_success:
  - mkdir out
  - docker run --rm -v $(pwd)/out:/tmp/out -ti wine.appimage cp Wine-x86_64.AppImage /tmp/Wine-x86_64.AppImage
  - wget -c "https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh"
  - bash  ./upload_rotate.sh "continuous" Wine-*x86_64.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
    - /^(?i:examples)/
